version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: blog-user
      POSTGRES_PASSWORD: blog123
      POSTGRES_DB: blog
    ports:
      - "5432:5432"